# -*- coding: utf-8 -*-
"""Corrected_vit_lime_explanations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xe0TaGqms9H_s926wVzzEF9fID5WqPw5
"""

!wget -O novel.py "https://raw.githubusercontent.com/CasperSkovholt/MasterThesis/main/novel.py"

!ls -lh
!head -20 novel.py

input_file = "/content/novel.py"
output_file = "/content/novel_fixed.py"

with open(input_file, "r", encoding="utf-8") as f:
    lines = f.readlines()

fixed_lines = []
for line in lines:
    stripped = line.lstrip()
    if stripped.startswith("!pip install"):
        fixed_lines.append("# " + line)
    else:
        fixed_lines.append(line)

with open(output_file, "w", encoding="utf-8") as f:
    f.writelines(fixed_lines)

print("Fixed file saved as:", output_file)

!pip install -q kagglehub timm lime scikit-image opencv-python seaborn

import os
import shutil

for folder in ["/content/novel_approach", "/content/datasetsplit"]:
    if os.path.exists(folder):
        shutil.rmtree(folder)
        print("Deleted:", folder)

print("Ready for clean run.")

import os
print(os.getcwd())

# Commented out IPython magic to ensure Python compatibility.
# %run /content/novel_fixed.py

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report, confusion_matrix
from google.colab import files

correct_target_names = [label_to_class[i] for i in sorted(label_to_class.keys())]

# Save corrected classification report
report_dict = classification_report(
    all_labels,
    all_preds,
    labels=sorted(label_to_class.keys()),
    target_names=correct_target_names,
    digits=4,
    output_dict=True
)

report_df = pd.DataFrame(report_dict).transpose()
report_df.to_csv("/content/corrected_vit_classification_report.csv")

# Save corrected confusion matrix counts
cm = confusion_matrix(
    all_labels,
    all_preds,
    labels=sorted(label_to_class.keys())
)

cm_df = pd.DataFrame(
    cm,
    index=correct_target_names,
    columns=correct_target_names
)

cm_df.to_csv("/content/corrected_vit_confusion_matrix_counts.csv")

# Save corrected confusion matrix percentages
cm_percent = cm.astype("float") / cm.sum(axis=1)[:, np.newaxis]

cm_percent_df = pd.DataFrame(
    cm_percent,
    index=correct_target_names,
    columns=correct_target_names
)

cm_percent_df.to_csv("/content/corrected_vit_confusion_matrix_percent.csv")

# Save corrected confusion matrix image
plt.figure(figsize=(8, 6))
sns.heatmap(
    cm_percent,
    annot=True,
    fmt=".4f",
    cmap="Blues",
    xticklabels=correct_target_names,
    yticklabels=correct_target_names
)

plt.xticks(rotation=45)
plt.xlabel("Predicted label")
plt.ylabel("True label")
plt.title("Corrected ViT-B/16 Confusion Matrix")
plt.tight_layout()
plt.savefig("/content/corrected_vit_confusion_matrix.png", dpi=300, bbox_inches="tight")
plt.show()

print("Saved files:")
print("/content/corrected_vit_classification_report.csv")
print("/content/corrected_vit_confusion_matrix_counts.csv")
print("/content/corrected_vit_confusion_matrix_percent.csv")
print("/content/corrected_vit_confusion_matrix.png")

files.download("/content/corrected_vit_classification_report.csv")
files.download("/content/corrected_vit_confusion_matrix_counts.csv")
files.download("/content/corrected_vit_confusion_matrix_percent.csv")
files.download("/content/corrected_vit_confusion_matrix.png")

torch.save(model.state_dict(), "/content/corrected_vit_model.pth")
files.download("/content/corrected_vit_model.pth")

print("model exists:", "model" in globals())
print("test_dataset exists:", "test_dataset" in globals())
print("label_to_class exists:", "label_to_class" in globals())
print("val_test_transforms exists:", "val_test_transforms" in globals())
print("device exists:", "device" in globals())

!pip install -q lime scikit-image

from lime import lime_image
from skimage.segmentation import mark_boundaries
from PIL import Image
import numpy as np
import matplotlib.pyplot as plt
import torch
import os

model.eval()

class_names = [label_to_class[i] for i in sorted(label_to_class.keys())]
print("Class names:", class_names)

def predict_fn(images):
    model.eval()

    batch = torch.stack([
        val_test_transforms(Image.fromarray(img)).to(device)
        for img in images
    ])

    with torch.no_grad():
        outputs = model(batch)
        probs = torch.nn.functional.softmax(outputs, dim=1)

    return probs.cpu().numpy()

explainer = lime_image.LimeImageExplainer()

print("LIME setup ready.")

image_paths = []

for class_id in sorted(label_to_class.keys()):
    class_prefix = f"{class_id}_"
    selected_path = None

    for path in test_dataset.image_paths:
        folder_name = os.path.basename(os.path.dirname(path))

        if folder_name.startswith(class_prefix):
            selected_path = path
            break

    if selected_path is not None:
        image_paths.append(selected_path)
    else:
        print("No test image found for:", class_id, label_to_class[class_id])

print("Selected LIME image paths:")
for p in image_paths:
    print(p)

originals = []
explanations = []
titles = []

for path in image_paths:
    print("Processing:", path)

    img = Image.open(path).convert("RGB")
    img_resized = img.resize((224, 224))

    transformed_img = val_test_transforms(img_resized)
    input_tensor = transformed_img.unsqueeze(0).to(device)

    with torch.no_grad():
        output = model(input_tensor)
        probs = torch.nn.functional.softmax(output, dim=1)
        pred_class = torch.argmax(probs, dim=1).item()
        confidence = probs[0][pred_class].item()

    explanation = explainer.explain_instance(
        image=np.array(img_resized),
        classifier_fn=predict_fn,
        top_labels=4,
        hide_color=0,
        num_samples=3000
    )

    temp, mask = explanation.get_image_and_mask(
        label=pred_class,
        positive_only=True,
        hide_rest=True,
        num_features=8,
        min_weight=0.1
    )

    originals.append(img_resized)
    explanations.append((temp, mask))
    titles.append(f"{class_names[pred_class]} ({confidence*100:.2f}%)")

print("LIME explanations completed.")

fig, axes = plt.subplots(len(originals), 2, figsize=(10, 4 * len(originals)))

if len(originals) == 1:
    axes = np.array([axes])

for i in range(len(originals)):
    axes[i, 0].imshow(originals[i])
    axes[i, 0].set_title(f"Original Image {i+1}")
    axes[i, 0].axis("off")

    temp, mask = explanations[i]
    axes[i, 1].imshow(mark_boundaries(temp, mask))
    axes[i, 1].set_title(f"LIME: {titles[i]}")
    axes[i, 1].axis("off")

plt.tight_layout()
plt.savefig("/content/corrected_vit_lime_explanations.png", dpi=300, bbox_inches="tight")
plt.show()

print("Saved LIME figure:")
print("/content/corrected_vit_lime_explanations.png")

from google.colab import files
files.download("/content/corrected_vit_lime_explanations.png")